// env file data
const ENV_DATA = Object.freeze({
  BACKEND_PORT: process.env.BACKEND_PORT,
  DATA_BASE_NAME: process.env.DATA_BASE_NAME,
  DATA_BASE_USER_NAME: process.env.DATA_BASE_USER_NAME,
  DATA_BASE_PASSOWRD: process.env.DATA_BASE_PASSOWRD,
  DATA_BASE_HOST: process.env.DATA_BASE_HOST,
  DB_PORT: process.env.DB_PORT,
  REFRESH_TOKEN_EXPIRY_TIME: "1d",
  ACCESS_TOKEN_EXPIRY_TIME: "1h",
  CUSTOMER_ACCESS_TOKEN_EXPIRY_TIME:"30d",
  FORGOT_TOKEN_EXPIRY_TIME: "15m",
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  FORGET_PASSWORD_LINK: process.env.FORGET_PASSWORD_LINK,
  MAIL_SENDER: process.env.MAIL_SENDER,
  MAIL_PASS: process.env.MAIL_PASS,
  OTP_VALIDATION_TIME:"1.2",

  // s3 bucket credentials
  S3BUCKET_ACCESSKEY: process.env.S3_AWS_ACCESS_KEY_ID,
  S3BUCKET_SECRETACCESSKEY: process.env.S3_AWS_SECRET_KEY_ID,
  S3BUCKET_REGION: process.env.S3_BUCKET_REGION,
  S3BUCKET_NAME: process.env.S3_AWS_BUCKET,
});

module.exports = { ENV_DATA };
